import type { Scenario } from './types';

export const initRepoScenario: Scenario = {
  id: 'init-repo',
  title: '1. Your First Repository',
  description: 'Initialize a repo, then choose exactly what of your AI co-builder\'s output to save',
  narrative:
    "You're kicking off a new project with an AI assistant as your co-builder. The AI can draft code fast — but you're still the one in charge of what actually becomes part of your project. Git is how you stay in control: it tracks your work and lets you decide, file by file, what enters your history.\n\nIn this scenario you'll set up a repository, let the AI draft a file, and then practice the skill that matters most when you build with AI: saving the good work and leaving the junk behind.",
  difficulty: 'beginner',
  order: 1,
  tags: ['basics', 'init', 'add', 'commit', 'status'],
  setup: (_engine) => {
    // Clean slate - user will init themselves
  },
  docLinks: [
    { label: 'git init docs', url: 'https://git-scm.com/docs/git-init' },
    { label: 'git add docs', url: 'https://git-scm.com/docs/git-add' },
    { label: 'git commit docs', url: 'https://git-scm.com/docs/git-commit' },
    { label: 'git status docs', url: 'https://git-scm.com/docs/git-status' },
  ],
  tutorialSteps: [
    {
      id: 'init',
      title: 'Initialize a Git Repository',
      narrative: "Every git project starts with `git init`. This creates a hidden `.git` folder that tracks all your changes. Think of it as turning on git's memory for this project folder — before you let an AI generate anything, you want a way to track and undo it.",
      expectedCommand: 'git init',
      hint: 'Type: git init',
      validation: (state) => state.initialized,
      helpContent: {
        explanation: '`git init` creates a new Git repository. It sets up all the internal data structures git needs to track your files.',
        why: "Without initializing, git has no idea your folder exists. This is always the first step in a new project — and it's what makes everything the AI writes reviewable and reversible.",
        docsUrl: 'https://git-scm.com/docs/git-init',
      },
      milestone: { id: 'first-init', title: 'Repository Created' },
    },
    {
      id: 'create-file',
      title: 'Let the AI Draft a File',
      narrative: "Your AI co-builder just wrote the first version of your app. Let's create that file. In a real session, this is the code the AI generated for you — the starting point you'll review and build on.",
      expectedCommand: 'echo "// AI-generated starter code" > app.js',
      hint: 'Try: echo "// AI-generated starter code" > app.js',
      isBashOnly: true,
      autoCommand: 'echo "// AI-generated starter code" > app.js',
      validation: (state) => state.workingDirectory.has('app.js'),
      helpContent: {
        explanation: '`echo "text" > file` creates a new file with the given content. This is a shell command, not a git command. Right now `app.js` just sits in your Working Directory — git sees it, but hasn\'t saved it.',
        why: "AI assistants produce files quickly. Treat every one as a draft: it lives in your Working Directory until you decide whether it deserves a place in your history.",
      },
    },
    {
      id: 'create-junk',
      title: 'The AI Left Some Junk Behind',
      narrative: "AI tools often leave scratch and temp files behind while they work. Here's one. It's clutter — you do not want it in your project's history.",
      expectedCommand: 'echo "temporary junk" > scratch.tmp',
      hint: 'Try: echo "temporary junk" > scratch.tmp',
      isBashOnly: true,
      autoCommand: 'echo "temporary junk" > scratch.tmp',
      validation: (state) => state.workingDirectory.has('scratch.tmp'),
      helpContent: {
        explanation: 'Now you have two untracked files: `app.js` (the code you want) and `scratch.tmp` (junk you don\'t). Both are sitting in your Working Directory.',
        why: "This is the everyday reality of building with AI: useful output and throwaway output land side by side. Git lets you keep them separate.",
      },
    },
    {
      id: 'check-status',
      title: 'Check the Status',
      narrative: "Before you save anything, ask git what it sees. `git status` is your best friend — you'll use it constantly to understand what state your files are in.",
      expectedCommand: 'git status',
      hint: 'Type: git status',
      validation: (_state, lastCommand) => lastCommand.trim() === 'git status',
      helpContent: {
        explanation: '`git status` shows which files are tracked, changed, or staged. Both `app.js` and `scratch.tmp` show up as "untracked" — git knows they exist but isn\'t saving either one yet.',
        why: 'Getting in the habit of checking status before you commit is how you avoid accidentally saving the wrong thing. When an AI has been generating files, a quick status check tells you exactly what showed up.',
        docsUrl: 'https://git-scm.com/docs/git-status',
      },
    },
    {
      id: 'stage-file',
      title: 'Stage Only What You Want to Keep',
      narrative: "This is the moment that matters. Git won't decide for you — you decide what of the AI's output enters history. Name the file so you stage just the good one: `git add app.js`. Avoid `git add .` here — that would sweep up `scratch.tmp` too. Watch the diagram: only `app.js` should move to the Staging Area.",
      expectedCommand: 'git add app.js',
      hint: 'Type: git add app.js',
      validation: (state) => state.stagingArea.has('app.js') && !state.stagingArea.has('scratch.tmp'),
      helpContent: {
        explanation: '`git add app.js` moves that one file from your Working Directory into the Staging Area (the "index"). Naming the file — instead of using `git add .` — keeps `scratch.tmp` out.',
        why: "Staging is where you decide what of the AI's output enters history. The AI can write ten files; you choose which ones are worth keeping. That editorial control is the whole point — you own what goes into your project, not the AI.",
        docsUrl: 'https://git-scm.com/docs/git-add',
        relatedCommands: ['git status', 'git reset HEAD'],
      },
      milestone: { id: 'first-stage', title: 'First File Staged' },
    },
    {
      id: 'commit',
      title: 'Make Your First Commit',
      narrative: "Now save this snapshot permanently. A commit is like a save point in a game — you can always come back to it. Use `git commit -m` followed by a message describing what you did.",
      expectedCommand: /^git commit/,
      hint: 'Try: git commit -m "Add AI-drafted starter code"',
      validation: (state) => state.commits.size > 0,
      helpContent: {
        explanation: '`git commit -m "message"` takes everything in the Staging Area — just `app.js` — and creates a permanent snapshot. Because you never staged `scratch.tmp`, it stays out of the commit entirely.',
        why: 'Commits are the core of git. Each one is a snapshot of your project at a moment in time. When you build with AI, your commit message is also your record of the decision you made about what to keep.',
        docsUrl: 'https://git-scm.com/docs/git-commit',
        relatedCommands: ['git log'],
      },
      milestone: { id: 'first-commit', title: 'First Commit!' },
    },
    {
      id: 'view-log',
      title: 'View Your History',
      narrative: "Congratulations! You've made your first commit. Let's look at the project history with `git log` to see it recorded forever.",
      expectedCommand: 'git log',
      hint: 'Type: git log (or git log --oneline for a compact view)',
      validation: (_state, lastCommand) => lastCommand.trim().startsWith('git log'),
      helpContent: {
        explanation: '`git log` shows the history of commits in your repository. Each entry shows the commit hash (a unique ID), author, date, and message. Your first commit contains `app.js` and nothing else.',
        why: "The log is how you navigate your project's history. It's a timeline of the decisions you made — including the one where you kept the AI's good file and dropped the junk.",
        docsUrl: 'https://git-scm.com/docs/git-log',
        relatedCommands: ['git log --oneline', 'git reflog'],
      },
      milestone: { id: 'first-log', title: 'Explored the Log' },
    },
  ],
};
