import type { Scenario } from './types';

export const initRepoScenario: Scenario = {
  id: 'init-repo',
  title: '1. Your First Repository',
  description: 'Initialize a repo, create files, and make your first commit',
  narrative: "You're starting a brand new project. Before you can use git to track your work, you need to set up a repository. Let's walk through the basics: initializing a repo, creating some files, staging them, and making your very first commit.",
  difficulty: 'beginner',
  order: 1,
  tags: ['basics', 'init', 'add', 'commit', 'status'],
  setup: (_engine) => {
    // Clean slate - user will init themselves
  },
  docLinks: [
    { label: 'git init docs', url: 'https://git-scm.com/docs/git-init' },
    { label: 'git add docs', url: 'https://git-scm.com/docs/git-add' },
    { label: 'git commit docs', url: 'https://git-scm.com/docs/git-commit' },
    { label: 'git status docs', url: 'https://git-scm.com/docs/git-status' },
  ],
  tutorialSteps: [
    {
      id: 'init',
      title: 'Initialize a Git Repository',
      narrative: "Every git project starts with `git init`. This creates a hidden `.git` folder that tracks all your changes. Think of it as turning on git's memory for this project folder.",
      expectedCommand: 'git init',
      hint: 'Type: git init',
      validation: (state) => state.initialized,
      helpContent: {
        explanation: '`git init` creates a new Git repository. It sets up all the internal data structures git needs to track your files.',
        why: 'Without initializing, git has no idea your folder exists. This is always the first step in a new project.',
        docsUrl: 'https://git-scm.com/docs/git-init',
      },
      milestone: { id: 'first-init', title: 'Repository Created' },
    },
    {
      id: 'create-file',
      title: 'Create a File',
      narrative: "Now let's create a file for git to track. In a real project, this would be your source code. Use the `touch` command to create an empty file, or `echo` to create one with content.",
      expectedCommand: 'echo "Hello, World!" > hello.txt',
      hint: 'Try: echo "Hello, World!" > hello.txt',
      isBashOnly: true,
      autoCommand: 'echo "Hello, World!" > hello.txt',
      validation: (state) => state.workingDirectory.size > 0,
      helpContent: {
        explanation: '`echo "text" > file` creates a new file with the given content. `touch file` creates an empty file. These are shell commands, not git commands.',
        why: 'Git tracks files, so you need at least one file before git can do anything useful.',
      },
    },
    {
      id: 'check-status',
      title: 'Check the Status',
      narrative: "Before we do anything else, let's ask git what it sees. `git status` is your best friend - you'll use it constantly to understand what state your files are in.",
      expectedCommand: 'git status',
      hint: 'Type: git status',
      validation: (_state, lastCommand) => lastCommand.trim() === 'git status',
      helpContent: {
        explanation: '`git status` shows which files are tracked, which have changes, and which are staged for commit. The file shows as "untracked" because git knows it exists but isn\'t tracking it yet.',
        why: 'Getting in the habit of checking status before and after operations prevents mistakes. It\'s like looking both ways before crossing the street.',
        docsUrl: 'https://git-scm.com/docs/git-status',
        relatedCommands: ['git diff'],
      },
    },
    {
      id: 'stage-file',
      title: 'Stage Your File',
      narrative: "Your file is in the Working Directory but git isn't tracking it yet. Use `git add` to move it to the Staging Area. Watch the visual diagram - you'll see the file move!",
      expectedCommand: /^git add/,
      hint: 'Try: git add hello.txt (or git add . to add everything)',
      validation: (state) => state.stagingArea.size > 0,
      helpContent: {
        explanation: '`git add` moves files from your Working Directory to the Staging Area (also called the "index"). Think of staging as packing a box - you choose exactly what goes in before sealing it.',
        why: "Staging lets you be selective about what you commit. Maybe you changed 5 files but only want to commit 2 of them right now. Staging gives you that control.",
        docsUrl: 'https://git-scm.com/docs/git-add',
        relatedCommands: ['git reset HEAD', 'git status'],
      },
      milestone: { id: 'first-stage', title: 'First File Staged' },
    },
    {
      id: 'commit',
      title: 'Make Your First Commit',
      narrative: "Now let's save this snapshot permanently. A commit is like a save point in a game - you can always come back to it. Use `git commit -m` followed by a message describing what you did.",
      expectedCommand: /^git commit/,
      hint: 'Try: git commit -m "Initial commit"',
      validation: (state) => state.commits.size > 0,
      helpContent: {
        explanation: '`git commit -m "message"` takes everything in the Staging Area and creates a permanent snapshot (a "commit"). The `-m` flag lets you add a message describing what changed.',
        why: 'Commits are the core of git. Each one is a snapshot of your project at a moment in time. Good commit messages help you (and others) understand the history of your project.',
        docsUrl: 'https://git-scm.com/docs/git-commit',
        relatedCommands: ['git log', 'git diff --staged'],
      },
      milestone: { id: 'first-commit', title: 'First Commit!' },
    },
    {
      id: 'view-log',
      title: 'View Your History',
      narrative: "Congratulations! You've made your first commit. Let's look at the project history with `git log` to see it recorded forever.",
      expectedCommand: 'git log',
      hint: 'Type: git log (or git log --oneline for a compact view)',
      validation: (_state, lastCommand) => lastCommand.trim().startsWith('git log'),
      helpContent: {
        explanation: '`git log` shows the history of commits in your repository. Each entry shows the commit hash (a unique ID), author, date, and message.',
        why: "The log is how you navigate your project's history. It's like a detailed timeline of every change ever made.",
        docsUrl: 'https://git-scm.com/docs/git-log',
        relatedCommands: ['git log --oneline', 'git reflog'],
      },
      milestone: { id: 'first-log', title: 'Explored the Log' },
    },
  ],
};
